In [2]:
import numpy as np   # importing library of numpy

In [11]:
a = np.array([1,3,4,5,77])  # initializing array of a and then print the array
a


array([ 1,  3,  4,  5, 77])

In [12]:
type(a)   # checking type of array = one dimension array or vector    1dimension array= vector

numpy.ndarray

In [13]:
len(a) # checking the how many element is present in the array`

5

In [32]:
a[3] # checking the element on the 3 place

5

In [33]:
a[2:] # printing the elements from place 2 to last place i.e total 5 elements from 2 to 5 print elements

array([ 4,  5, 77])

In [24]:
b = np.array([[1,2,3,4,5], [6,7,8,9,10], [11,12,13,14,15]])
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [18]:
type(b) # nd.array means 1dimension array and 2dimension array

numpy.ndarray

In [19]:
len(b)

3

In [35]:
b[2]

array([11, 12, 13, 14, 15])

In [38]:
b[0:3] # printing the total elements in array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [46]:
c = np.array([[1,2,3],[4,5,6],[7,8,9],
              [1,2,3],[4,5,6],[7,8,9],
              [1,2,3],[4,5,6],[7,8,9]])
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
type(c)

numpy.ndarray

In [44]:
len(c)

9

In [57]:
n = np.arange(24).reshape(2,3,4)
n

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [49]:
type(n)

numpy.ndarray

In [46]:
food = np.array(["raita","biryani","qurma","pakorray"]) # 1D array
food

array(['raita', 'biryani', 'qurma', 'pakorray'], dtype='<U8')

In [47]:
food_price = np.array([10,100,300,50])  #1D array
food_price

array([ 10, 100, 300,  50])

In [48]:
len(food) #length of elements in food array 

4

In [49]:
len(food_price) #length of elements in food_price array 

4

In [50]:
food[2] # element on 2 place in food array 

'qurma'

In [51]:
food_price[3] #element on 3 place in food array 

50

In [52]:
food_price.mean() # finding mean of food_price array

115.0

In [53]:
food_price.max() # max value in food_price array

300

In [59]:
food_price.sum() # sum of all the elements in food_price array

460

In [66]:
np.zeros(10)     # defining array automatically with 0 elements whatever you want i.e (10) or (200)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [67]:
np.ones(20) # defining array automatically with 1 elements whatever you want i.e (20) or (200)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [69]:
np.empty(10) # defining empty array of 10 elements

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [70]:
np.arange(100) # defining array of 100 elements automatically

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [75]:
np.arange(2,20) # definig array automatically start from 2 and goes to 20 elements.

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [83]:
np.arange(2,100,2,) #definig array automatically start from 2 and goes to 100 elements and skip 2 elements amoung them

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68,
       70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [93]:
np.linspace(0,100, num=50) # linespace

array([  0.        ,   2.04081633,   4.08163265,   6.12244898,
         8.16326531,  10.20408163,  12.24489796,  14.28571429,
        16.32653061,  18.36734694,  20.40816327,  22.44897959,
        24.48979592,  26.53061224,  28.57142857,  30.6122449 ,
        32.65306122,  34.69387755,  36.73469388,  38.7755102 ,
        40.81632653,  42.85714286,  44.89795918,  46.93877551,
        48.97959184,  51.02040816,  53.06122449,  55.10204082,
        57.14285714,  59.18367347,  61.2244898 ,  63.26530612,
        65.30612245,  67.34693878,  69.3877551 ,  71.42857143,
        73.46938776,  75.51020408,  77.55102041,  79.59183673,
        81.63265306,  83.67346939,  85.71428571,  87.75510204,
        89.79591837,  91.83673469,  93.87755102,  95.91836735,
        97.95918367, 100.        ])

In [94]:
np.ones(20, dtype=np.int32) # specifing datatype of an array of its elements into integer

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [96]:
np.ones(20, dtype=np.float64) # specifing datatype of an array of its elements into float

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [112]:
w = np.array([23,45,68,22,56,86,24,54])
w

array([23, 45, 68, 22, 56, 86, 24, 54])

In [123]:
o=np.array([3,45,645,7,8,8,9,55,3])
o

array([  3,  45, 645,   7,   8,   8,   9,  55,   3])

In [116]:
np.sort(w)

array([22, 23, 24, 45, 54, 56, 68, 86])

In [125]:
np.concatenate((o,w))  # adding two array of o,w together.

array([  3,  45, 645,   7,   8,   8,   9,  55,   3,  23,  45,  68,  22,
        56,  86,  24,  54])

# 2-D Arrays

In [130]:
e = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
e

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [131]:
f = np.array([[2,3,4,3],[2,6,4,3],[2,4,8,5],[9,0,6,4]])
f

array([[2, 3, 4, 3],
       [2, 6, 4, 3],
       [2, 4, 8, 5],
       [9, 0, 6, 4]])

In [142]:
np.concatenate((e,f),axis=1) # adding two e,f 2-D array each other.

array([[ 1,  2,  3,  4,  2,  3,  4,  3],
       [ 5,  6,  7,  8,  2,  6,  4,  3],
       [ 9, 10, 11, 12,  2,  4,  8,  5],
       [13, 14, 15, 16,  9,  0,  6,  4]])

In [143]:
np.ndim(f) #finding what "f" array are consists of dimensions i.e 1D, 2D, or 3D.

2

In [144]:
np.ndim(e) #finding what "e" array are consists of dimensions i.e 1D, 2D, or 3D.

2

# 3-D Array

In [151]:
u = np.array([[[1,2,3],[4,5,6]],
              
             [[3,2,1],[6,5,4]],
              
             [[2,3,1],[7,8,9]]])
u

array([[[1, 2, 3],
        [4, 5, 6]],

       [[3, 2, 1],
        [6, 5, 4]],

       [[2, 3, 1],
        [7, 8, 9]]])

In [152]:
np.ndim(u)

3

In [154]:
np.size(u) # to find how many elements are avialed in "u" array.

18

In [155]:
np.shape(u) # to find the shape means that 3by3 elements, two rows and three colums

(3, 2, 3)

In [176]:
v = np.arange(9)
v


array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [190]:
p=v.reshape(3,3) # reshaping array of v into 3by3 order (3*3=9)
p 

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
o = np.arange(49)
o

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48])

In [6]:
o.reshape(7,7) # Reshaping the array to  7*7   i.e 7 Rows and 7 culomns

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47, 48]])

In [8]:
u = np.array([[1,2,3,4],
      [5,6,7,8],
      [1,2,3,4]])
u

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [12]:
np.ndim(u)

2

In [16]:
np.reshape(u, newshape=(1,12), order='c')   # ordering and new shape to the "u" array

array([[1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4]])

In [ ]:
# 1D array into 2D`

In [17]:
i = np.array([1,2,3,4,5,6,7,8,9])
i

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.shape(i)

(9,)

In [25]:
p=i[:,np.newaxis]  #1D array to 2D (culomn wise )
p

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [24]:
np.shape(p) # Shape of array

(1, 9)

In [26]:
p=i[np.newaxis,:]  #1D array to 2D (Row wise )
p

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [28]:
p=np.arange(25)
p

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [32]:
p[3:16] # Slicing of 3 to 16 elements of "p" array

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [33]:
p

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [35]:
p*50 # multiplying 50 to "p" array

array([   0,   50,  100,  150,  200,  250,  300,  350,  400,  450,  500,
        550,  600,  650,  700,  750,  800,  850,  900,  950, 1000, 1050,
       1100, 1150, 1200])

In [36]:
p+50 # adding 50 to "p" array

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74])

In [37]:
np.sum(p) # sum all the elements of "p" array

300

In [38]:
np.mean(p) # finding mean of "p" array

12.0

In [49]:
h = np.array([[33,66,54,67,43,32,67],
              [33,45,32,667,888,54,897]])
h

array([[ 33,  66,  54,  67,  43,  32,  67],
       [ 33,  45,  32, 667, 888,  54, 897]])

In [50]:
np.ndim(h)

2

In [52]:
np.divide(h,2) # divide by "2" of "h" array

array([[ 16.5,  33. ,  27. ,  33.5,  21.5,  16. ,  33.5],
       [ 16.5,  22.5,  16. , 333.5, 444. ,  27. , 448.5]])

In [58]:
np.remainder(h,8) # Remainder of array "h" of each elements

array([[1, 2, 6, 3, 3, 0, 3],
       [1, 5, 0, 3, 0, 6, 1]], dtype=int32)

In [61]:
np.repeat(h,2) # Repeat each elements "2" times of array [h] as shown below

array([ 33,  33,  66,  66,  54,  54,  67,  67,  43,  43,  32,  32,  67,
        67,  33,  33,  45,  45,  32,  32, 667, 667, 888, 888,  54,  54,
       897, 897])